### ISSUE TITLE
Include information on GitHub runners setup in README.MD

### ISSUE THREAD

**Issue by pdewilde** [abcxyz/github-metrics-aggregator#168]
The "build" job in the ci.yml workflow uses a special group "Beefy" to run on, which behind the scenes is a GitHub large runner group (before adding larger runners, this step took over 5 minutes).

If this repo is forked, that step will hang as no "Beefy" runner group will exist. Documentation should describe how to make your own "Beefy" group, or that you can switch back to "ubuntu-latest" to use a default runner.

**Comment by sethvargo** [comment]
Alternative option: can `runs-on` accept dynamic input? For example, would the following work:

```yaml
jobs:
  do-something:
    runs-on: '${{ vars.runner || "ubuntu-latest" }}'
```
